version: "3.3"

services:
  mysql:
    image: mysql:8.3.0
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 10s
      retries: 10
  redis:
    image: redis:7.2
    restart: unless-stopped
  mongodb:
    image: mongo:4.4.0
    restart: unless-stopped
    volumes:
      - mongodb_data:/data/db
  server:
    image: ghcr.io/minetoblend/osu-cad-server:master
    restart: always
    env_file:
      - .env
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
      mongodb:
        condition: service_started
    links:
      - mysql
      - redis
      - mongodb
    volumes:
      - server_data:/app/packages/server/files
  frontend:
    image: ghcr.io/minetoblend/osu-cad-client:master
    restart: always
    env_file:
      - .env
    depends_on:
      server:
        condition: service_started
    links:
      - server
  caddy:
    image: caddy:2.7.6
    ports:
      - "80:80"
      - "443:443"
    restart: always
    environment:
      - HOSTNAME=${HOSTNAME}
    volumes:
      - ./docker/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
    links:
      - server

volumes:
  mysql_data:
  mongodb_data:
  server_data:
  caddy_data:
