version: "3.3"

services:
  mysql:
    image: mysql:8.3.0
    restart: always
    env_file:
      - .env
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
  redis:
    image: redis:7.2
    restart: always
  mongodb:
    image: mongo:4.4.0
    restart: always
    volumes:
      - mongodb_data:/data/db
  server:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - mysql
      - redis
      - mongodb

    links:
      - mysql
      - redis
      - mongodb
    volumes:
      - server_data:/app/packages/server/files
  caddy:
    image: caddy:2.7.6
    ports:
      - "80:80"
      - "443:443"
    environment:
      - HOSTNAME=${HOSTNAME}
    volumes:
      - ./docker/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
    links:
      - server

volumes:
  mysql_data:
  mongodb_data:
  server_data:
  caddy_data:
