name: Publish Docker image to GitHub Packages

on:
  push:
    branches: ["master"]
    paths-ignore: ["README.md"]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME_CLIENT: ${{ github.repository }}-client
  IMAGE_NAME_SERVER: ${{ github.repository }}-server
  BASEURL: https://osucad.com
  SSR_API_BASEURL: http://server:3000

jobs:
  docker:
    name: Build and push Docker images
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker Client Meta
        id: meta-client
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_CLIENT }}
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=ref,event=pr
            type=sha,prefix=

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push client
        uses: docker/build-push-action@v5
        with:
          file: Dockerfile
          context: .
          target: client-ssr
          build-args: |
            BASEURL=${{ env.BASEURL }}
            SSR_API_BASEURL=${{ env.SSR_API_BASEURL }}
          tags: ${{ steps.meta-client.outputs.tags }}
          labels: ${{ steps.meta-client.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: true
          
    
      - name: Docker Server Meta
        id: meta-server
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_SERVER }}
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=ref,event=pr
            type=sha,prefix=

      - name: Build and push server
        uses: docker/build-push-action@v5
        with:
          file: Dockerfile
          context: .
          target: server
          build-args: |
            BASEURL=${{ env.BASEURL }}
            SSR_API_BASEURL=${{ env.SSR_API_BASEURL }}
          tags: ${{ steps.meta-server.outputs.tags }}
          labels: ${{ steps.meta-server.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: true


